---
#This ansible playbook will remove an image

- hosts: localhost
  tasks:
    - name: Remove image 
      podman_image_v2:
         name: alpine
         state: absent 
      register: result

    - debug: var=result  
